# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 679)
        MainWindow.setMinimumSize(QtCore.QSize(1044, 679))
        MainWindow.setMaximumSize(QtCore.QSize(1044, 679))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.maplabel = QtWidgets.QLabel(self.centralwidget)
        self.maplabel.setMinimumSize(QtCore.QSize(1024, 512))
        self.maplabel.setMaximumSize(QtCore.QSize(1024, 512))
        self.maplabel.setObjectName("maplabel")
        self.verticalLayout_3.addWidget(self.maplabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mouseCountry = QtWidgets.QLabel(self.centralwidget)
        self.mouseCountry.setMinimumSize(QtCore.QSize(100, 0))
        self.mouseCountry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mouseCountry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mouseCountry.setObjectName("mouseCountry")
        self.horizontalLayout_5.addWidget(self.mouseCountry)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.confirmLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.confirmLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.confirmLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.confirmLineEdit.setObjectName("confirmLineEdit")
        self.horizontalLayout.addWidget(self.confirmLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.deathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.deathLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.deathLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.deathLineEdit.setObjectName("deathLineEdit")
        self.horizontalLayout_2.addWidget(self.deathLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.recoverLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.recoverLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.recoverLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.recoverLineEdit.setObjectName("recoverLineEdit")
        self.horizontalLayout_3.addWidget(self.recoverLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.datelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.datelineEdit.setMinimumSize(QtCore.QSize(160, 0))
        self.datelineEdit.setMaximumSize(QtCore.QSize(16, 16777215))
        self.datelineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.datelineEdit.setObjectName("datelineEdit")
        self.horizontalLayout_5.addWidget(self.datelineEdit)
        self.datehorizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.datehorizontalScrollBar.setMinimumSize(QtCore.QSize(100, 0))
        self.datehorizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.datehorizontalScrollBar.setObjectName("datehorizontalScrollBar")
        self.horizontalLayout_5.addWidget(self.datehorizontalScrollBar)
        spacerItem1 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_5.setStretch(1, 4)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(6, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.maplabel.setText(_translate("MainWindow", "TextLabel"))
        self.mouseCountry.setText(_translate("MainWindow", "Country"))
        self.label_2.setText(_translate("MainWindow", "Confirmed"))
        self.label_3.setText(_translate("MainWindow", "Deaths"))
        self.label_4.setText(_translate("MainWindow", "Recovered"))
        self.label.setText(_translate("MainWindow", "Date"))

